# Generated by Django 3.2 on 2022-02-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
    ]
